detectors:
  UtilityFunction:
    enabled: false

  IrresponsibleModule:
    enabled: false

directories:
  "spec":
    Attribute:
      enabled: false
    UncommunicativeModuleName:
      enabled: false
