require:
  - rubocop-performance

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - lib/jat.rb
  EnforcedStyle: compact

Style/LambdaCall:
  EnforcedStyle: braces

