require:
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/LambdaCall:
  EnforcedStyle: braces

Style/Documentation:
  Enabled: false
