inherit_from: ../.rubocop.yml

require: rubocop-rspec

Layout/EmptyLineBetweenDefs:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - features/**/*_spec.rb
