name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / ActiveRecord ${{ matrix.activerecord }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby: 
          - jruby-9.3.2
          - truffleruby
          - truffleruby+graalvm
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
        activerecord:
          - "5.2"
          - "6.1"
          - "7.0"
        exclude:
          - ruby: "2.5"
            activerecord: "7.0"
          - ruby: "2.6"
            activerecord: "7.0"
          - ruby: jruby-9.3.2
            activerecord: "7.0"
          - ruby: "3.0"
            activerecord: "5.2"
          - ruby: "3.1"
            activerecord: "5.2"
          - ruby: "3.1"
            activerecord: "6.1"

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.activerecord }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests and Check Coverage
        run: bundle exec rake

      # Check code standards only for latest MRI. It takes a lot of time for jruby or truffleruby
      - name: Check Code Standards
        if: startsWith(matrix.ruby, '3.1')
        run: bundle exec standardrb
